# -*- coding: utf-8 -*-
"""Generates parts/ara_js_03_scenes.js (SCENES + metrics/lens/trace/viz + timeline)."""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from scenes_data import CH_DEFAULTS, CHAPTERS, SCENES  # noqa: E402

ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, 'parts', 'ara_js_03_scenes.js')

FA_DIGITS = '۰۱۲۳۴۵۶۷۸۹'


def fa_num(n):
    return ''.join(FA_DIGITS[int(c)] if c.isdigit() else c for c in str(n))


def js_str(v):
    return "'" + str(v).replace('\\', '\\\\').replace("'", "\\'") + "'"


def main():
    if len(SCENES) != 75:
        raise SystemExit('expected 75 scenes, got %d' % len(SCENES))

    lines = []
    lines.append('/* ============ GENERATED BY build_scripts/gen_scenes.py — DO NOT EDIT ============ */')
    lines.append('/* ================= CHAPTER VISUAL MAP ================= */')
    lines.append('var CHCOL={')
    lines.append(','.join('%s:%s' % (js_str(k), js_str(v)) for k, v in CHAPTERS.items()))
    lines.append('};')
    lines.append('')
    lines.append('/* ================= 75 SCENES · جریان داده · منابع · فرایندهای داخلی ================= */')
    lines.append('/* tier: VERIFIED | FACT | CLAIM | INFERENCE | CONFLICT | UNKNOWN | PENDING */')
    lines.append('var SCENES=[')

    metrics, lens, trace, viz = [], [], [], []
    for i, s in enumerate(SCENES):
        num = i + 1
        # renumber title prefix
        ti = re.sub(r'^\d+\s*[—-]\s*', '', s['ti'])
        ti = '%s — %s' % (fa_num(num), ti)
        cam = s['cam']
        lines.append('{d:%d,ch:%s,ti:%s,' % (s['d'], js_str(s['ch']), js_str(ti)))
        lines.append(' sb:%s,' % js_str(s['sb']))
        lines.append(' cam:{cx:%s,cy:%s,zoom:%s,rot:%s},' % cam)
        lines.append(' hot:[%s],' % ','.join(js_str(h) for h in s['hot']))
        if s.get('fin'):
            lines.append(' fin:1,')
        lines.append(' card:{tx:%s,tr:%s,sr:%s}},' % (js_str(s['tx']), js_str(s['tr']), js_str(s['sr'])))

        d = CH_DEFAULTS[s['ch']]
        m = s.get('m') or d[0]
        l = s.get('l') or d[1]
        t = s.get('t') or d[2]
        metrics.append('[%s, %s, %s, %d]' % (js_str(m[0]), js_str(m[1]), js_str(m[2]), m[3]))
        lens.append('{r:%s,o:%s,c:%s,f:%s}' % tuple(js_str(x) for x in l))
        trace.append('[%s, %s, %s]' % tuple(js_str(x) for x in t))
        if s.get('v'):
            title, items = s['v']
            items_js = ','.join('[%s, %d, %s]' % (js_str(a), b, js_str(c)) for a, b, c in items)
            viz.append('{title:%s,items:[%s]}' % (js_str(title), items_js))
        else:
            viz.append('null')

    lines[-1] = lines[-1].rstrip(',')
    lines.append('];')
    lines.append('')
    lines.append('var SCENE_METRICS=[' + ', '.join(metrics) + '];')
    lines.append('var SCENE_LENS=[' + ', '.join(lens) + '];')
    lines.append('var SCENE_TRACE=[' + ', '.join(trace) + '];')
    lines.append('var SCENE_VIZ=[' + ', '.join(viz) + '];')
    lines.append('')
    lines.append('/* timeline: صحنه‌ها پشت‌سرهم و ممتد */')
    lines.append('var T0=[],ACC=0;')
    lines.append('for(var si=0;si<SCENES.length;si++){T0.push(ACC);SCENES[si].t0=ACC;ACC+=SCENES[si].d;}')
    lines.append('var END=ACC;')
    lines.append("var TIERCOL={VERIFIED:'#3ddc84',FACT:'#32d3ff',CLAIM:'#ffd166',INFERENCE:'#b892ff',CONFLICT:'#ff8a2b',UNKNOWN:'#7c8aa2',PENDING:'#f4698a'};")
    lines.append("var TIERFA={VERIFIED:'واقعیت تأییدشده',FACT:'واقعیت منبع‌دار',CLAIM:'ادعای عملیاتی',INFERENCE:'استنتاج مستند',CONFLICT:'تعارض داده',UNKNOWN:'نامعلوم',PENDING:'نیازمند اعتبارسنجی'};")
    lines.append('')
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines))
    total = sum(s['d'] for s in SCENES)
    print('wrote %s · %d scenes · %ds (%.1f min)' % (OUT, len(SCENES), total, total / 60.0))


if __name__ == '__main__':
    main()
